services:
  # PostgreSQL
  cadmus-biblio-pgsql:
    image: postgres
    container_name: cadmus-biblio-pgsql
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - 5432:5432
    networks:
      - cadmus-biblio-network
    # volumes:
      # - pgsql-vol:/var/lib/postgresql/data

  # MongoDB (authentication)
  cadmus-biblio-mongo:
    image: mongo
    container_name: cadmus-biblio-mongo
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
    command: mongod --logpath=/dev/null # --quiet
    ports:
      - 27017:27017
    networks:
      - cadmus-biblio-network

  # Biblio API
  cadmus-biblio-api:
    image: vedph2020/cadmus-biblio-api:6.0.1
    container_name: cadmus-biblio-api
    ports:
      - 61691:8080
    depends_on:
      - cadmus-biblio-mongo
      - cadmus-biblio-pgsql
    environment:
      - ASPNETCORE_URLS=http://+:8080
      - CONNECTIONSTRINGS__DEFAULT=mongodb://cadmus-biblio-mongo:27017/{0}
      - CONNECTIONSTRINGS__AUTH=Server=cadmus-biblio-pgsql;port=5432;Database={0};User Id=postgres;Password=postgres;Include Error Detail=True
      - CONNECTIONSTRINGS__BIBLIO=Server=cadmus-biblio-pgsql;port=5432;Database={0};User Id=postgres;Password=postgres;Include Error Detail=True
      - SEED__BIBLIODELAY=30
      - SERILOG__CONNECTIONSTRING=mongodb://cadmus-biblio-mongo:27017/{0}-log
      - STOCKUSERS__0__PASSWORD=P4ss-W0rd!
    networks:
      - cadmus-biblio-network

  # Biblio demo API
  cadmus-biblio-demo-api:
    image: vedph2020/cadmus-biblio-demo-api:7.0.0
    container_name: cadmus-biblio-demo-api
    ports:
      - 5034:8080
    depends_on:
      - cadmus-biblio-mongo
      - cadmus-biblio-pgsql
    environment:
      - ASPNETCORE_URLS=http://+:8080
      - CONNECTIONSTRINGS__DEFAULT=mongodb://cadmus-biblio-mongo:27017/{0}
      - CONNECTIONSTRINGS__AUTH=Server=cadmus-biblio-pgsql;port=5432;Database={0};User Id=postgres;Password=postgres;Include Error Detail=True
      - CONNECTIONSTRINGS__BIBLIO=Server=cadmus-biblio-pgsql;port=5432;Database={0};User Id=postgres;Password=postgres;Include Error Detail=True
      - SEED__DELAY=30
      - SERILOG__CONNECTIONSTRING=mongodb://cadmus-biblio-mongo:27017/{0}-log
      - STOCKUSERS__0__PASSWORD=P4ss-W0rd!
    networks:
      - cadmus-biblio-network

  # Biblio app
  cadmus-biblio-app:
    image: vedph2020/cadmus-biblio-shell:3.1.0
    container_name: cadmus-biblio-app
    ports:
      - 4200:80
    depends_on:
      - cadmus-biblio-api
      - cadmus-biblio-demo-api
    networks:
      - cadmus-biblio-network

networks:
  cadmus-biblio-network:
    driver: bridge

# volumes:
#   pgsql-vol:
